Inventory
SDev-2018/Alchemic-Forest pull request #17
Opened 2018-04-11 01:31 UTC by Mdaviet

This does not have #16 lights-camera implemented.  Once lights-camera is merged I will rebase master onto inventory which shouldn't change any functionality.

2018-04-11 02:54 UTC, EVanDyke requested changes
The HUD does not display updated log counts when a new log is collected.

2018-04-11 04:21 UTC, Mdaviet commented
Combined lighting with pickups, and counter should be working fine now.

2018-04-11 22:39 UTC, EVanDyke approved these changes

2018-04-13 00:33 UTC, mk10-13 approved these changes

2018-04-13 00:35 UTC, merged